<?php

namespace App\Model;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{




    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    protected $guarded = [];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function replies(){
        return $this->hasMany(Reply::class);
    }
    public function categories(){
        return $this->belongsTo(Category::class);
    }
    public function getPathAttribute(){
        return asset("api/question/$this->slug");
    }
}
