<?php

namespace App\Model;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * @property mixed replies
 */
class Question extends Model
{

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($question){

            $question->slug = Str::slug($question->title);

        });
    }
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    //protected $guarded = [];
    protected $fillable = ['title','body','slug','user_id','category_id'];

    protected $with = ['replies'];


    public function user(){
        return $this->belongsTo(User::class);
    }

    public function replies(){
        return $this->hasMany(Reply::class)->latest();
    }
    public function categories(){
        return $this->belongsTo(Category::class);
    }
    public function getPathAttribute(){
        return "question/$this->slug";
    }
}
